### ISSUE TITLE
Request: Mount with 4 Heatsets

### ISSUE THREAD

**Issue by LupoLoopy** [AdamV3D/RainbowShift#1]
Hi Adam!

Any chance of a version of the mount with 4 heatset points as opposed to the two and two static pins please? I prefer the look aesthetically.

Happy to work off the original CAD file, if that's easier? Whatever works for you.

Thanks for your work in this! So much easier than fashioning stuff myself

CT

**Comment by AdamV3D** [comment]
No worries, added.
